language: python
python:
  - "3.7"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
dist: trusty
sudo: required
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
services:
  - mysql
  - redis-server
  - rabbitmq
install:
  - pip setup.py install
script:
  - python -m unittest discover -s anthill/common/tests
